import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { marked } from 'marked';

const SITE_URL = 'https://dashchat.org';
const SITE_NAME = 'Dash Chat';
const POSTS_DIR = 'blog/posts';
const IMAGES_DIR = 'blog/images';
const OUT_DIR = 'public';
const BLOG_IMAGES_OUT = path.join(OUT_DIR, 'blog-images');

const REQUIRED_FIELDS = ['title', 'date', 'author', 'description'];

// Slugs that would clobber site files generated by Vite or kept in public/.
const RESERVED_SLUGS = new Set(['index', '404', 'blog', 'sitemap', 'rss']);

// A safe slug is lowercase letters, numbers and single hyphens only.
// Prevents path traversal (no slashes/dots) and odd URLs.
function isSafeSlug(slug) {
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug);
}

function readPosts() {
  if (!fs.existsSync(POSTS_DIR)) {
    console.warn(`Warning: ${POSTS_DIR} does not exist. No posts to build.`);
    return [];
  }

  const files = fs.readdirSync(POSTS_DIR).filter(f => f.endsWith('.md'));
  const posts = [];

  for (const file of files) {
    const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf-8');
    const { data, content } = matter(raw);
    const slug = file.replace(/\.md$/, '');

    if (!isSafeSlug(slug)) {
      console.warn(`Warning: ${file} has an unsafe slug "${slug}". Use only lowercase letters, numbers, and hyphens. Skipping.`);
      continue;
    }
    if (RESERVED_SLUGS.has(slug)) {
      console.warn(`Warning: ${file} uses reserved slug "${slug}" which would overwrite a site file. Skipping.`);
      continue;
    }

    const missing = REQUIRED_FIELDS.filter(f => !data[f]);
    if (missing.length > 0) {
      console.warn(`Warning: ${file} is missing required fields: ${missing.join(', ')}. Skipping.`);
      continue;
    }

    if (data.date instanceof Date) {
      data.date = data.date.toISOString().split('T')[0];
    }
    if (data.modified instanceof Date) {
      data.modified = data.modified.toISOString().split('T')[0];
    }

    posts.push({ slug, data, content, file });
  }

  posts.sort((a, b) => (b.data.date > a.data.date ? 1 : -1));
  return posts;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDate(dateStr) {
  const d = new Date(dateStr + 'T00:00:00Z');
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' });
}

function sharedStyles() {
  return `
    :root {
      --bg: #fcfcfc;
      --surface: #fff;
      --text: #111;
      --muted: #555;
      --faint: #888;
      --border: #e5e7eb;
      --accent: #1D4ED8;
      --accent-hover: #1e40af;
      --accent-light: #dbeafe;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #0b0c0f;
        --surface: #111318;
        --text: #e5e7eb;
        --muted: #94a3b8;
        --faint: #64748b;
        --border: #1e293b;
        --accent: #60a5fa;
        --accent-hover: #93c5fd;
        --accent-light: #1e3a5f;
      }
    }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { scroll-behavior: smooth; }
    body {
      font-family: "Rubik", system-ui, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
    }
    nav {
      position: fixed; top: 0; left: 0; right: 0; z-index: 100;
      background: var(--bg);
      border-bottom: 1px solid var(--border);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
    }
    @supports (backdrop-filter: blur(12px)) {
      nav { background: color-mix(in srgb, var(--bg) 85%, transparent); }
    }
    .nav-inner {
      max-width: 960px; margin: 0 auto; padding: 0 24px;
      height: 56px; display: flex; align-items: center; justify-content: flex-end;
    }
    .nav-links { display: flex; align-items: center; gap: 20px; }
    .nav-links a {
      font-size: 0.9rem; font-weight: 500;
      color: var(--muted); text-decoration: none; transition: color 0.15s;
    }
    .nav-links a:hover { color: var(--text); }
    .nav-links .gh-link { display: flex; align-items: center; color: var(--muted); transition: color 0.15s; }
    .nav-links .gh-link:hover { color: var(--text); }
    .nav-links .gh-link svg { display: block; }
    footer {
      border-top: 1px solid var(--border);
      padding: 32px 24px; text-align: center;
      font-size: 0.85rem; color: var(--faint);
    }
    footer a { color: var(--faint); text-decoration: underline; text-underline-offset: 2px; }
    footer a:hover { color: var(--muted); }
  `;
}

function navHtml() {
  return `
  <nav>
    <div class="nav-inner">
      <div class="nav-links">
        <a href="/blog">Blog</a>
        <a href="/#get-involved">Get involved</a>
        <a href="https://github.com/dash-chat" target="_blank" rel="noopener noreferrer" class="gh-link" title="GitHub">
          <svg width="22" height="22" viewBox="0 0 16 16" fill="currentColor"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0016 8c0-4.42-3.58-8-8-8z"/></svg>
        </a>
      </div>
    </div>
  </nav>`;
}

function footerHtml() {
  return `
  <footer>
    Open source under the <a href="https://github.com/dash-chat/dash-chat/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">AGPL-3.0</a> license.
  </footer>`;
}

function jsonLd(post) {
  const url = `${SITE_URL}/${post.slug}`;
  const graph = [
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      "url": SITE_URL,
      "name": SITE_NAME,
    },
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#organization`,
      "name": SITE_NAME,
      "url": SITE_URL,
    },
    {
      "@type": "WebPage",
      "@id": `${url}/#webpage`,
      "url": url,
      "name": post.data.title,
      "isPartOf": { "@id": `${SITE_URL}/#website` },
      "datePublished": post.data.date,
      ...(post.data.modified ? { "dateModified": post.data.modified } : {}),
    },
    {
      "@type": "BlogPosting",
      "@id": `${url}/#article`,
      "mainEntityOfPage": { "@id": `${url}/#webpage` },
      "headline": post.data.title,
      "description": post.data.description,
      "datePublished": post.data.date,
      ...(post.data.modified ? { "dateModified": post.data.modified } : {}),
      "author": { "@type": "Person", "name": post.data.author },
      "publisher": { "@id": `${SITE_URL}/#organization` },
      ...(post.data.image ? { "image": `${SITE_URL}${post.data.image}` } : {}),
    },
  ];

  return JSON.stringify({ "@context": "https://schema.org", "@graph": graph })
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');
}

function buildPostHtml(post) {
  const url = `${SITE_URL}/${post.slug}`;
  const htmlContent = marked(post.content);
  const escapedTitle = escapeHtml(post.data.title);
  const escapedDesc = escapeHtml(post.data.description);
  const imageTag = post.data.image ? `${SITE_URL}${post.data.image}` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapedTitle} — ${SITE_NAME}</title>
  <meta name="description" content="${escapedDesc}" />
  <link rel="canonical" href="${url}" />
  <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
  <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <link rel="alternate" type="application/rss+xml" title="${SITE_NAME} RSS" href="${SITE_URL}/rss.xml" />

  <!-- Open Graph -->
  <meta property="og:type" content="article" />
  <meta property="og:title" content="${escapedTitle}" />
  <meta property="og:description" content="${escapedDesc}" />
  <meta property="og:url" content="${url}" />
  <meta property="article:published_time" content="${post.data.date}" />${imageTag ? `\n  <meta property="og:image" content="${escapeHtml(imageTag)}" />` : ''}

  <!-- Twitter Card -->
  <meta name="twitter:card" content="${imageTag ? 'summary_large_image' : 'summary'}" />
  <meta name="twitter:title" content="${escapedTitle}" />
  <meta name="twitter:description" content="${escapedDesc}" />${imageTag ? `\n  <meta name="twitter:image" content="${escapeHtml(imageTag)}" />` : ''}

  <!-- JSON-LD -->
  <script type="application/ld+json">${jsonLd(post)}</script>

  <style>
    ${sharedStyles()}
    .post-container {
      max-width: 720px; margin: 0 auto; padding: 0 24px;
    }
    .post-header {
      padding: 100px 0 40px;
    }
    .post-header h1 {
      font-size: clamp(1.75rem, 4vw, 2.5rem);
      font-weight: 700; line-height: 1.2;
      letter-spacing: -0.02em; margin-bottom: 12px;
    }
    .post-meta {
      color: var(--muted); font-size: 0.9rem;
    }
    .post-content {
      padding-bottom: 80px;
    }
    .post-content h2 {
      font-size: 1.5rem; font-weight: 600;
      margin: 40px 0 16px; letter-spacing: -0.01em;
    }
    .post-content h3 {
      font-size: 1.2rem; font-weight: 600;
      margin: 32px 0 12px;
    }
    .post-content p {
      margin-bottom: 16px; color: var(--text);
      font-size: 1.05rem; line-height: 1.7;
    }
    .post-content ul, .post-content ol {
      margin: 0 0 16px 24px; font-size: 1.05rem; line-height: 1.7;
    }
    .post-content li { margin-bottom: 6px; }
    .post-content blockquote {
      border-left: 3px solid var(--accent);
      padding: 12px 20px; margin: 24px 0;
      color: var(--muted); font-style: italic;
      background: var(--surface); border-radius: 0 6px 6px 0;
    }
    .post-content code {
      font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
      background: var(--surface); border: 1px solid var(--border);
      padding: 2px 6px; border-radius: 4px; font-size: 0.9em;
    }
    .post-content pre {
      background: var(--surface); border: 1px solid var(--border);
      border-radius: 8px; padding: 16px 20px;
      overflow-x: auto; margin: 24px 0;
    }
    .post-content pre code {
      background: none; border: none; padding: 0;
      font-size: 0.88rem; line-height: 1.6;
    }
    .post-content img {
      max-width: 100%; height: auto;
      border-radius: 8px; margin: 24px 0;
    }
    .post-content hr {
      border: none; border-top: 1px solid var(--border);
      margin: 40px 0;
    }
    .post-content a {
      color: var(--accent); text-decoration: underline;
      text-underline-offset: 2px;
    }
    .post-content a:hover { color: var(--accent-hover); }
    .back-link {
      display: inline-block; margin-top: 16px; margin-bottom: 32px;
      font-size: 0.9rem; color: var(--muted); text-decoration: none;
    }
    .back-link:hover { color: var(--text); }
  </style>
</head>
<body>
  ${navHtml()}

  <article>
    <div class="post-container">
      <header class="post-header">
        <a href="/blog" class="back-link">&larr; All posts</a>
        <h1>${escapedTitle}</h1>
        <div class="post-meta">${escapeHtml(post.data.author)} &middot; ${formatDate(post.data.date)}</div>
      </header>
      <div class="post-content">
        ${htmlContent}
      </div>
    </div>
  </article>

  ${footerHtml()}
</body>
</html>`;
}

function buildBlogIndex(posts) {
  const postItems = posts.map(p => `
        <a href="/${p.slug}" class="post-item">
          <h3>${escapeHtml(p.data.title)}</h3>
          <div class="post-item-meta">${escapeHtml(p.data.author)} &middot; ${formatDate(p.data.date)}</div>
          <p>${escapeHtml(p.data.description)}</p>
        </a>`).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Blog — ${SITE_NAME}</title>
  <meta name="description" content="Updates and thoughts from the ${SITE_NAME} team." />
  <link rel="canonical" href="${SITE_URL}/blog" />
  <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
  <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <link rel="alternate" type="application/rss+xml" title="${SITE_NAME} RSS" href="${SITE_URL}/rss.xml" />

  <meta property="og:type" content="website" />
  <meta property="og:title" content="Blog — ${SITE_NAME}" />
  <meta property="og:description" content="Updates and thoughts from the ${SITE_NAME} team." />
  <meta property="og:url" content="${SITE_URL}/blog" />

  <style>
    ${sharedStyles()}
    .blog-container {
      max-width: 720px; margin: 0 auto; padding: 0 24px;
    }
    .blog-header {
      padding: 100px 0 40px;
    }
    .blog-header h1 {
      font-size: clamp(1.75rem, 4vw, 2.5rem);
      font-weight: 700; letter-spacing: -0.02em;
    }
    .post-list {
      padding-bottom: 80px;
      display: flex; flex-direction: column; gap: 0;
    }
    .post-item {
      display: block; text-decoration: none; color: inherit;
      padding: 24px 0;
      border-bottom: 1px solid var(--border);
      transition: opacity 0.15s;
    }
    .post-item:first-child { border-top: 1px solid var(--border); }
    .post-item:hover { opacity: 0.75; }
    .post-item h3 {
      font-size: 1.2rem; font-weight: 600;
      margin-bottom: 4px; color: var(--text);
    }
    .post-item-meta {
      font-size: 0.85rem; color: var(--faint);
      margin-bottom: 8px;
    }
    .post-item p {
      font-size: 0.95rem; color: var(--muted);
      line-height: 1.5; margin: 0;
    }
  </style>
</head>
<body>
  ${navHtml()}

  <div class="blog-container">
    <header class="blog-header">
      <h1>Blog</h1>
    </header>
    <div class="post-list">
${postItems}
    </div>
  </div>

  ${footerHtml()}
</body>
</html>`;
}

function buildSitemap(posts) {
  const urls = [
    { loc: SITE_URL + '/', priority: '1.0' },
    { loc: SITE_URL + '/blog', priority: '0.8' },
    ...posts.map(p => ({
      loc: `${SITE_URL}/${p.slug}`,
      lastmod: p.data.modified || p.data.date,
      priority: '0.6',
    })),
  ];

  const entries = urls.map(u => `  <url>
    <loc>${u.loc}</loc>${u.lastmod ? `\n    <lastmod>${u.lastmod}</lastmod>` : ''}
    <priority>${u.priority}</priority>
  </url>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>`;
}

function buildRss(posts) {
  const recentPosts = posts.slice(0, 20);

  const items = recentPosts.map(p => {
    const url = `${SITE_URL}/${p.slug}`;
    const pubDate = new Date(p.data.date + 'T00:00:00Z').toUTCString();
    return `    <item>
      <title>${escapeHtml(p.data.title)}</title>
      <link>${url}</link>
      <guid>${url}</guid>
      <pubDate>${pubDate}</pubDate>
      <description>${escapeHtml(p.data.description)}</description>
    </item>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${SITE_NAME}</title>
    <link>${SITE_URL}</link>
    <description>Updates from ${SITE_NAME}</description>
    <language>en</language>
    <atom:link href="${SITE_URL}/rss.xml" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>`;
}

function copyImages() {
  if (!fs.existsSync(IMAGES_DIR)) return;

  if (!fs.existsSync(BLOG_IMAGES_OUT)) {
    fs.mkdirSync(BLOG_IMAGES_OUT, { recursive: true });
  }

  const files = fs.readdirSync(IMAGES_DIR);
  for (const file of files) {
    fs.copyFileSync(path.join(IMAGES_DIR, file), path.join(BLOG_IMAGES_OUT, file));
  }
  if (files.length > 0) {
    console.log(`Copied ${files.length} image(s) to ${BLOG_IMAGES_OUT}`);
  }
}

function main() {
  console.log('Building blog...');

  const posts = readPosts();
  console.log(`Found ${posts.length} post(s)`);

  if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
  }

  for (const post of posts) {
    const html = buildPostHtml(post);
    const outPath = path.join(OUT_DIR, `${post.slug}.html`);
    fs.writeFileSync(outPath, html);
    console.log(`  → ${outPath}`);
  }

  const indexHtml = buildBlogIndex(posts);
  fs.writeFileSync(path.join(OUT_DIR, 'blog.html'), indexHtml);
  console.log(`  → ${path.join(OUT_DIR, 'blog.html')}`);

  const sitemap = buildSitemap(posts);
  fs.writeFileSync(path.join(OUT_DIR, 'sitemap.xml'), sitemap);
  console.log(`  → ${path.join(OUT_DIR, 'sitemap.xml')}`);

  const rss = buildRss(posts);
  fs.writeFileSync(path.join(OUT_DIR, 'rss.xml'), rss);
  console.log(`  → ${path.join(OUT_DIR, 'rss.xml')}`);

  copyImages();

  console.log('Blog build complete!');
}

main();
